[package]
name = "dungeon_crawl_p2p"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.15", features = ["bevy_window"] }
# locked to 0.2.97 to be compatible w/ wasm-server-runner
wasm-bindgen = "=0.2.97"

[profile.dev.package."*"]
opt-level = 2
